[package]
name = "integration_tests"
version = "0.0.0"
authors = ["Exonum Team <exonum@bitfury.com>"]
publish = false
edition = "2018"

build = "build.rs"

[dependencies]
exonum = { version = "0.13.0-rc.2", git = "https://github.com/exonum/exonum", rev = "a85fdc22" }
exonum-derive = { version = "0.13.0-rc.2", git = "https://github.com/exonum/exonum", rev = "a85fdc22" }
exonum-merkledb = { version = "0.13.0-rc.2", git = "https://github.com/exonum/exonum", rev = "a85fdc22" }
exonum-proto = { version = "0.13.0-rc.2", git = "https://github.com/exonum/exonum", rev = "a85fdc22" }

actix-web = { version = "0.7.19", default-features = false }
hex = "0.4.0"
failure = "0.1.6"
protobuf = "2.10.0"
rand = "0.7.2"
rand_chacha = "0.2.1"
serde = "1.0"
serde_derive = "1.0"
uuid = "0.8.1"

[build-dependencies]
exonum-build = { version = "0.13.0-rc.2", git = "https://github.com/exonum/exonum", rev = "a85fdc22" }
