[package]
name = "integration_tests"
version = "0.0.0"
authors = ["Exonum Team <exonum@bitfury.com>"]
publish = false
edition = "2018"

build = "build.rs"

[dependencies]
exonum = { version = "0.11.0", git = "https://github.com/exonum/exonum", rev = "10451e1" }
exonum-merkledb = { version = "0.11.0", git = "https://github.com/exonum/exonum", rev = "10451e1" }
exonum-derive = { version = "0.11.0", git = "https://github.com/exonum/exonum", rev = "10451e1" }
hex = "0.3.2"
failure = "0.1.5"
protobuf = "2.6.2"
rand = "0.6"
rocket = "0.4.1"
rocket_codegen = "0.4.1"
serde = "1.0"
serde_derive = "1.0"
uuid = "0.7.4"

[dependencies.rocket_contrib]
version = "0.4.1"
default-features = false
features = ["json"]

[build-dependencies]
exonum-build = "0.11.0"
